### ISSUE TITLE
beta values hop at horizon level (sometimes)

### ISSUE THREAD

**Issue by bognick** [Full-Tilt/Full-Tilt#23]
Hi there and congrats for your library,

I have noticed that sometimes the FullTilt reported beta values (Euler) are hoping around the horizon level (90º). In the vr_test demo while the camera is super smooth the reported beta values usually hop around the horizon level (never hitting 90º). I wonder how it's possible that the camera pitch movement is super smooth while the Euler beta value hops? I'm not sure this is a bug but in my application I need a consistent pitch value around the horizon.

I also noticed the following: 
1. I may have to reload the page in order for the issue to emerge. At first load its possible that the beta values are just fine around the horizon. Also some devices pinpoint the issue more clearly.
2. When locking the device orientation in portrait mode and turning the device in landscape mode the alpha, beta, gamma values behave more smoothly, the pitch is correctly reported at the horizon level and the orientation values do not interfere with each other. The only issue in this case is that the magnetic north is offset by 90º.

Best,
Nikos

**Comment by unsalted** [comment]
Same issue, glad to see i'm not alone.

**Comment by unsalted** [comment]
I was digging think this is covered in #2

**Comment by bognick** [comment]
It seems you're right. It crossed my mind that this kind of behavior could be due to Gimbal lock but then again I thought the Gimbal lock wouldn't be allowed to occur at an angle so likely to be used (horizon). 

Firefox for Android was up until the previous version still robust at the horizon level, but the current version is aligned with the other browsers in having issues at the horizon level. 

The issue of reliable pitch, yaw, roll angles at the horizon level remains but it's not for FullTilt.js to solve so I'm closing this.
